# Generated by Django 3.1.1 on 2020-09-19 15:59

from django.db import migrations, models
import pessoas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('cargo', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to=pessoas.models.upload_to)),
            ],
        ),
    ]
