# Generated by Django 3.1.1 on 2020-09-19 17:16

from django.db import migrations, models
import pessoas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='foto',
            field=models.ImageField(blank=True, upload_to=pessoas.models.upload_to, verbose_name='foto'),
        ),
    ]
